### ISSUE TITLE
Failed build due to changelog error

### ISSUE THREAD

**Issue by heucke** [open-switch/opx-db-sql#17]
https://github.com/open-switch/opx-db-sql/blob/e71bdaeae61cf4eb2b95006b32d8c534a977186a/debian/changelog#L5

```
dpkg-parsechangelog: warning:     debian/changelog(l5): invalid abbreviated month name 'June'
--
  | LINE:  -- Dell EMC <ops-dev@lists.openswitch.net>  Wed, 22 June 2017 11:41:31 -0700
```

Updated `git-buildpackage` and this date formatting issue is now an error.

**Comment by Tejaswi-Goel** [comment]
Corrected it.
